import { FC, ReactNode, useEffect, useState } from "react";

import Head from "next/head";
import { useRouter } from "next/router";

import { AuthMiddleware, useAuth } from "@/app/api/hook/useAuth";
import { globalCss } from "@/stitches.config";
import { ExitIcon, PersonIcon } from "@radix-ui/react-icons";

import { Header } from "../header";
import { Logo } from "../logo";
import { Avatar, AvatarFallback, AvatarImage } from "../ui/avatar";
import { Box } from "../ui/box";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "../ui/dropdownMenu";

interface ILayout {
  title: string;
  alignH?: "left" | "center" | "right" | undefined;
  alignV?: "top" | "center" | "bottom" | undefined;
  middleware: AuthMiddleware;
  children: ReactNode;
}

const globalStyles = globalCss({
  body: {
    background: "$bg",
  },
});

const Layout: FC<ILayout> = ({
  children,
  middleware,
  title,
  alignH = "center",
  alignV = "center",
}) => {
  globalStyles();
  const router = useRouter();
  
  const { user, username, logout } = useAuth({
    middleware,
    redirectIfAuthenticated: "/",
  });

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header>
          <div className="header__left" onClick={() => router.push("/")}>
            <Logo />
          </div>
          {user ? (
            <div className="header__right">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <div className="header__user">
                    <Avatar size="small">
                      {user?.avatar ? (
                        <AvatarImage src={user.avatar} alt={username.full} />
                      ) : (
                        ""
                      )}

                      <AvatarFallback>{username.initials}</AvatarFallback>
                    </Avatar>

                    <span className="header__user-name">{username.full}</span>
                  </div>
                </DropdownMenuTrigger>

                <DropdownMenuContent sideOffset={5}>
                  <DropdownMenuItem onSelect={() => router.push("/profile")}>
                    <PersonIcon />
                    Edit profile
                  </DropdownMenuItem>
                  <DropdownMenuItem onSelect={logout}>
                    <ExitIcon />
                    logout
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          ) : (
            ""
          )}
        </Header>
        <Box type="fullScreen" alignH={alignH} alignV={alignV}>
          {children}
        </Box>
      </main>
    </div>
  );
};

export default Layout;
